In [1]:
import numpy as np

In [2]:
my_list = list(range(100000))
type(my_list)

list

In [2]:
my_arr = np.arange(1000000)
type(my_arr)

numpy.ndarray

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
%time
for _ in range (10):
    my_arr2 = my_arr * 2

Wall time: 0 ns


In [12]:
data1 =np.random.randn(2,3) # 2rows 3 columns 
data1

array([[-0.59451921, -1.15183078,  0.33692708],
       [-1.20296047, -1.91212452, -0.04403774]])

In [16]:
data1.ndim

2

In [15]:
data2 =np.random.randn(2,3,3) # 2rows 3 columns 
data2

array([[[ 0.16814964, -1.95520008,  1.50740675],
        [-2.14556094,  0.99822894,  0.2939955 ],
        [ 1.27003671,  1.71321048,  0.63710756]],

       [[ 0.87753641, -2.28964125,  0.56181934],
        [ 0.3707962 , -1.38204943, -0.2697849 ],
        [ 2.07920207,  1.7639898 , -0.59258455]]])

In [9]:
data1 = data


In [17]:
data1.dot(data2)

array([[[ 2.79926471,  0.5898402 , -1.02015655],
        [-0.24826725,  3.54745873, -0.22292362]],

       [[ 3.84437278,  0.36784446, -2.40356351],
        [-1.85621348,  5.31931641, -0.13388804]]])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.empty((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
print(data1.shape)
print(data1.dtype)
np.ones_like(data1)

(2, 3)
float64


array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
a1 = np.random.randn(2,2)
a2 = np.random.randn(2,2)

In [25]:
a1 > a2

array([[False, False],
       [ True,  True]])

In [26]:
# index and list
# Vector and Tensor dimention
q=np.array([1,2,3,4,5,6])

In [27]:
q.shape

(6,)

In [28]:
#Answer (6,)means it has 6 dimensional vector but 1 dimentional Tensor

In [29]:
arr1 = np.array((1,))

In [30]:
data9 = np.random.randn(6,3)

In [31]:
data9

array([[ 1.87916499, -0.28606218, -1.00470199],
       [ 1.24639694,  0.46352523,  0.08598604],
       [ 0.61398126,  0.84911277, -0.03170063],
       [-0.30253178, -1.23299735,  0.22869319],
       [ 0.66479428,  0.10406432,  2.60696042],
       [ 0.32687723,  0.06349721,  1.5104079 ]])

In [32]:
data9 *10

array([[ 18.79164994,  -2.86062184, -10.04701985],
       [ 12.46396943,   4.63525233,   0.85986037],
       [  6.13981264,   8.49112768,  -0.31700626],
       [ -3.02531782, -12.32997348,   2.28693194],
       [  6.64794277,   1.04064315,  26.06960419],
       [  3.26877228,   0.63497208,  15.10407903]])

In [33]:
data9 + data9

array([[ 3.75832999, -0.57212437, -2.00940397],
       [ 2.49279389,  0.92705047,  0.17197207],
       [ 1.22796253,  1.69822554, -0.06340125],
       [-0.60506356, -2.4659947 ,  0.45738639],
       [ 1.32958855,  0.20812863,  5.21392084],
       [ 0.65375446,  0.12699442,  3.02081581]])

In [34]:
data9.shape

(6, 3)

In [35]:
data9.dtype

dtype('float64')

In [37]:
# Indexing and Slicing
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr[5]

5

In [39]:
arr[5:8]

array([5, 6, 7])

In [40]:
arr[5:8] = 12

In [41]:
arr[5:8]

array([12, 12, 12])

In [42]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [43]:
arr_slice = arr[5:8]

In [44]:
arr_slice

array([12, 12, 12])

In [45]:
arr_slice[1] =12345

In [46]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [47]:
arr_slice[:]=64

In [48]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [49]:
#Two Dimentional Arrays

In [50]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [51]:
arr2d[2]

array([7, 8, 9])

In [52]:
arr2d[0][2]

3

In [53]:
arr2d[0,2]

3

In [54]:
#Three Dimentional Arrays

In [56]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [57]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])