In [5]:
import numpy as np

In [2]:
arr1 = np.arange(12) #One Dimention array
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
arr2 = np.randm(3,4)
arr2

AttributeError: module 'numpy' has no attribute 'randm'

In [10]:
arr3=np.arange(10,1001,10)

In [11]:
arr3

array([  10,   20,   30,   40,   50,   60,   70,   80,   90,  100,  110,
        120,  130,  140,  150,  160,  170,  180,  190,  200,  210,  220,
        230,  240,  250,  260,  270,  280,  290,  300,  310,  320,  330,
        340,  350,  360,  370,  380,  390,  400,  410,  420,  430,  440,
        450,  460,  470,  480,  490,  500,  510,  520,  530,  540,  550,
        560,  570,  580,  590,  600,  610,  620,  630,  640,  650,  660,
        670,  680,  690,  700,  710,  720,  730,  740,  750,  760,  770,
        780,  790,  800,  810,  820,  830,  840,  850,  860,  870,  880,
        890,  900,  910,  920,  930,  940,  950,  960,  970,  980,  990,
       1000])

In [12]:
len(arr3)

100

In [17]:
arr4=np.arange(12).reshape(3,4)
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
arr5=arr4.resize(2,6)

In [29]:
arr6= np.arange(1,25).reshape(2,3,4)
arr6

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [31]:
arr6[0,-1,2:]

array([11, 12])

In [38]:
arr6[1][0:4]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [39]:
arr6[1,0::2,0:3:2]

array([[13, 15],
       [21, 23]])

In [45]:
#otherway to select 13,15, 21,23
arr6[1,[0,2],0:3:2]  #0:3:2 (here 2 is staking)

array([[13, 15],
       [21, 23]])

In [46]:
arr7=np.arange(100).reshape(4,5,5)

In [47]:
arr7

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [55]:
arr7[2,0:5,0:4:4]

array([[50],
       [55],
       [60],
       [65],
       [70]])

In [6]:
import pandas as pd

In [61]:
obj = pd.Series([2,33,5,10,55,77])

In [62]:
obj

0     2
1    33
2     5
3    10
4    55
5    77
dtype: int64

In [60]:
type(obj)

pandas.core.series.Series

In [63]:
obj.values

array([ 2, 33,  5, 10, 55, 77], dtype=int64)

In [64]:
obj.index

RangeIndex(start=0, stop=6, step=1)

In [69]:
obj2=pd.Series([4,7,-5,3], index=['d','b','c','a'])

In [70]:
obj2

d    4
b    7
c   -5
a    3
dtype: int64

In [71]:
#Value get
obj2['a']

3

In [72]:
#Value Change
obj2['d'] = 6

In [73]:
obj2

d    6
b    7
c   -5
a    3
dtype: int64

In [74]:
obj2[['c','a','d']]

c   -5
a    3
d    6
dtype: int64

In [75]:
obj2>2

d     True
b     True
c    False
a     True
dtype: bool

In [77]:
obj2[obj2>0]

d    6
b    7
a    3
dtype: int64

In [78]:
obj2 * 2

d    12
b    14
c   -10
a     6
dtype: int64

In [79]:
np.exp(obj2)

d     403.428793
b    1096.633158
c       0.006738
a      20.085537
dtype: float64

In [80]:
'b' in obj2

True

In [82]:
'e' in obj2

False

In [83]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [84]:
sdata = pd.Series(sdata)

In [85]:
sdata

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [86]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [87]:
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [88]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [90]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [7]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [8]:
frame=pd.DataFrame(data)

In [9]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [10]:
frame.head() #by default it shows 5 rows

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [11]:
frame.tail() #by default it show 5 rows

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [12]:
pd.DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [13]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four','five', 'six'])

In [14]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [15]:
frame2['debt']=5

In [16]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     5
two    2001    Ohio  1.7     5
three  2002    Ohio  3.6     5
four   2001  Nevada  2.4     5
five   2002  Nevada  2.9     5
six    2003  Nevada  3.2     5

In [17]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [18]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [21]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [22]:
frame2.loc['one']

year     2000
state    Ohio
pop       1.5
debt        5
Name: one, dtype: object

In [24]:
frame2.iloc[0:2]

year state  pop  debt
one  2000  Ohio  1.5     5
two  2001  Ohio  1.7     5

In [31]:
frame2.loc['one':'three']

year state  pop  debt
one    2000  Ohio  1.5     5
two    2001  Ohio  1.7     5
three  2002  Ohio  3.6     5

In [32]:
frame2.loc['one':"four":2] #here 2 is a step

year state  pop  debt
one    2000  Ohio  1.5     5
three  2002  Ohio  3.6     5

In [33]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     5
two    2001    Ohio  1.7     5
three  2002    Ohio  3.6     5
four   2001  Nevada  2.4     5
five   2002  Nevada  2.9     5
six    2003  Nevada  3.2     5

In [34]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [35]:
frame2['debt'] = val

In [36]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [43]:
data2= {'city': ['Lahore', 'Karachi', 'Isl', 'Hyderabad', 'Larkana', 'Multan'],
'users': [5000, 8000, 4000, 6000, 7000, 2000],
'Consumption': [10,16,8,12,14,4]}

In [44]:
frame3=pd.DataFrame(data2)

In [45]:
frame3

city  users  Consumption
0     Lahore   5000           10
1    Karachi   8000           16
2        Isl   4000            8
3  Hyderabad   6000           12
4    Larkana   7000           14
5     Multan   2000            4

In [46]:
frame3=pd.DataFrame(data2, columns=['city',"users",'Consumption','time duration'])

In [47]:
frame3

city  users  Consumption time duration
0     Lahore   5000           10           NaN
1    Karachi   8000           16           NaN
2        Isl   4000            8           NaN
3  Hyderabad   6000           12           NaN
4    Larkana   7000           14           NaN
5     Multan   2000            4           NaN

In [50]:
frame4=pd.DataFrame(index=['one','two',"three",'four','five'], columns=['city','users','Consumption', 'time duration'])

In [51]:
frame4

city users Consumption time duration
one    NaN   NaN         NaN           NaN
two    NaN   NaN         NaN           NaN
three  NaN   NaN         NaN           NaN
four   NaN   NaN         NaN           NaN
five   NaN   NaN         NaN           NaN

In [52]:
frame4["city"]=[6,2,5,4,9]

In [53]:
frame4

city users Consumption time duration
one       6   NaN         NaN           NaN
two       2   NaN         NaN           NaN
three     5   NaN         NaN           NaN
four      4   NaN         NaN           NaN
five      9   NaN         NaN           NaN

In [54]:
frame4["users"]=[550,650,750,850,950]

In [55]:
frame4

city  users Consumption time duration
one       6    550         NaN           NaN
two       2    650         NaN           NaN
three     5    750         NaN           NaN
four      4    850         NaN           NaN
five      9    950         NaN           NaN