In [12]:
import numpy as np
#Indexing and Slicing

In [6]:
arr2 = np.arange(1,25).reshape(6,4)

In [7]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [18]:
arr2[2:4,2:4]

array([[11, 12],
       [15, 16]])

In [22]:
arr2[2:3,:2]

array([[ 9, 10]])

In [24]:
arr2[:,2:3]

array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]])

In [29]:
arr2[2:3,1:3]

array([[10, 11]])

In [30]:
arr2[2,3]

12

In [31]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [32]:
arr2[[1,4]]

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [37]:
arr2[[2,4],[1,3]]

array([10, 20])

In [38]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [39]:
data

array([[ 0.7465585 , -1.0904567 , -0.57513924,  1.2413517 ],
       [ 0.64698277, -1.08755393, -0.34914202,  1.48049648],
       [-0.51442328,  0.16900847, -0.0530518 , -0.08288881],
       [-0.91654138, -0.58207546,  2.28072962, -0.12606379],
       [-0.31584296,  0.11555549, -1.08704545,  0.2511636 ],
       [-0.97578636, -0.96262271, -0.40906856,  0.13855566],
       [ 0.61367406,  0.27728163, -0.83638815, -0.45000426]])

In [40]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [41]:
data[names == 'Bob', 2:]

array([[-0.57513924,  1.2413517 ],
       [ 2.28072962, -0.12606379]])

In [42]:
data[names == 'Bob', 3]

array([ 1.2413517 , -0.12606379])

In [43]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [44]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [45]:
arr2>15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# bool

In [49]:
arr5 = np.arange(32).reshape((8,4))

In [50]:
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [52]:
arr5[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [53]:
#Transpose
arr5.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [14]:
arr6 = np.arange(42).reshape((6,7))

In [15]:
arr6

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])

In [19]:
#Verticle increase by row, and horizontal increase by columns
arr7 = np.array([[1,2,3],[4,5,6]])
arr7

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr8 = np.array([[7,8,9],[10,11,12]])
arr8

array([[ 7,  8,  9],
       [10, 11, 12]])

In [22]:
np.concatenate((arr7,arr8))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
np.concatenate([arr7, arr8], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [25]:
np.vstack((arr7,arr8))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
np.hstack((arr7,arr8))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [31]:
#SPLIT
arr9 = np.arange(1,13).reshape((4,3))

In [32]:
arr9

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
np.vsplit(arr9,2)

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]])]

In [35]:
np.hsplit(arr9,3)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]), array([[ 2],
        [ 5],
        [ 8],
        [11]]), array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [36]:
arr = np.arange(3)

In [37]:
arr

array([0, 1, 2])

In [38]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [39]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [40]:
np.tile(arr,2)

array([0, 1, 2, 0, 1, 2])